//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordAddIn1.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<Projects>
  <Project Name=""Recipies"">
    <Intentions>
      <Intention Name=""Genaral Info"" Tag=""gen"">
        <Entities>
          <Entity Tag=""gen-author"" Name=""Author"" />
          <Entity Tag=""gen-occasion"" Name=""Occasion"" />
          <Entity Tag=""gen-subject"" Name=""Subject"" />
        </Entities>
      </Intention>
      <Intention Name=""Ingredient"" Tag=""ing"">
        <Entities>
          <Entity Tag=""ing-name"" Name=""Name"" />
          <Entity Tag=""ing-quantity"" Name=""Quantity"" />
          <Entity Tag=""ing-form"" Name=""Form"" />
        </Entities>
      </Intention>
    </Intentions>
  </Project>
  <Project Name=""Support"">
    <Intentions>
      <Intention Name=""Header"" Tag=""gen"">
        <Entities>
          <Entity Tag=""gen-author"" Name=""Author"" />
          <Entity Tag=""gen-sent"" Name=""Sent Date"" />
          <Entity Tag=""gen-subject"" Name=""Subject"" />
        </Entities>
      </Intention>
      <Intention Name=""Product"" Tag=""ing"">
        <Entities>
          <Entity Tag=""ing-name"" Name=""Product Name"" />
          <Entity Tag=""ing-quantity"" Name=""Version"" />
          <Entity Tag=""ing-form"" Name=""Operating System"" />
        </Entities>
      </Intention>
    </Intentions>
  </Project>
</Projects>")]
        public global::System.Xml.XmlDocument Projects {
            get {
                return ((global::System.Xml.XmlDocument)(this["Projects"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Recipies")]
        public string Recent {
            get {
                return ((string)(this["Recent"]));
            }
            set {
                this["Recent"] = value;
            }
        }
    }
}
